name: wallet_apps
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  rxdart: ^0.25.0
  
  # Database
  shared_preferences: ^0.5.12+2

  # Backend
  http: 
  connectivity:
  connectivity_wrapper:
  # firebase_remote_config: ^0.4.0+2
  async: ^2.4.2

  # Image service
  image_picker:
  path_provider:
  # image:
  
  flutter_svg: ^0.19.0
  intl:
  image_cropper:
  flutter_image_compress:
 
  # Camera
  barcode_scan:
  qr_flutter: 
  qr_code_scanner: ^0.3.0

  # Share
  share_extend:

  # Chart
  flutter_circular_chart:
  syncfusion_flutter_charts:
  charts_flutter:
  fl_chart: ^0.12.0
  pie_chart: 4.0.1

  #Indecator
  percent_indicator:

  # Icons
  # outline_material_icons:
  # line_icons: ^0.2.0
  # line_awesome_icons:
  line_awesome_flutter:

  pinput: ^1.0.0
  # flutter_datetime_picker:
  transparent_image: 
  slider_button:
  # pull_to_refresh:  
  autocomplete_textfield:
  date_format:
  flutter_launcher_icons:
  device_preview:
  store_redirect:
  # fluttercontactpicker: ^3.1.0
  share:
  flutter_sms: ^2.1.1

  # Apps Configuration
  rename:
  package_info: 

  #Authenticatioin & Verification
  local_auth: ^0.6.3+3
  sms_autofill:
  permission_handler: ^5.0.1+1

  #for secure wallet function
  polkawallet_sdk: ^0.0.8
  animations: ^1.1.2

  #Contact
  contacts_service: ^0.4.6 
  fluttercontactpicker: ^4.2.1
  
  #animation
  flare_flutter:

  responsive_framework: ^0.0.8

  circular_check_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/sld_icon.png"
  ios: true
  android: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/icons/
    - assets/images_slide/

    # Animation Flare
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Roman.otf
        
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  #module: 
   # androidX: true
